name: Get all articles

on:
    push:
        branches: [main]

jobs:
  download-articles:
    runs-on: ubuntu-latest
    steps:
      - name: verif code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: execute downloas script
        run: |
          chmod +x script/get_article.sh
          ./script/get_article.sh

      - name: commit new articles
        run: |
          chmod +x  script/push.sh
          ./script/push.sh
